const NAV=['Home','Learning','Practice','Performance','Assets','Profile','Settings'];
const KEY='sciencehub.phase4.state.v1';
const defaultState={route:'Home',layout:{},profile:{picture:null,pictureChangedAt:null},permissions:{},history:[],settings:{notifications:true,offline:true}};
let state=load();
function load(){try{return {...defaultState,...JSON.parse(localStorage.getItem(KEY)||'{}')}}catch{return structuredClone(defaultState)}}
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function log(type,detail){state.history.push({time:new Date().toISOString(),type,detail});state.history=state.history.slice(-100);save()}
function canChangePicture(){return !state.profile.pictureChangedAt || Date.now()-new Date(state.profile.pictureChangedAt).getTime()>=15*86400000}
function render(){const route=state.route;document.querySelector('#app').innerHTML=`<div class="shell"><header class="top"><div class="brand">ScienceHub.io</div><input id="search" class="search" placeholder="Search permitted ScienceHub data…" aria-label="Search"></header><main><section class="panel"><h1>${route}</h1><p class="muted">Phase 4 runnable foundation · ${navigator.onLine?'Online':'Offline'} mode</p>${content(route)}</section></main><nav class="nav">${NAV.map(n=>`<button class="${n===route?'active':''}" data-route="${n}">${n}</button>`).join('')}</nav></div>`;document.querySelectorAll('[data-route]').forEach(b=>b.onclick=()=>{state.route=b.dataset.route;save();render()});document.querySelector('#search').oninput=e=>{if(e.target.value.trim())log('search','User initiated permission-aware search: '+e.target.value.trim())}}
function content(r){const map={Home:`<div class="grid"><div class="card"><b>Today’s Overview</b><p class="muted">Foundation ready for academic modules.</p></div><div class="card"><b>Continue Learning</b><p class="muted">Learning engine integration is planned for the next implementation stage.</p></div><div class="card"><b>System Status</b><p class="status">Local storage: ready · PWA: ready · Upgrade Guard: monitoring shell</p></div></div>`,Learning:card('Learning hierarchy','Subject → Chapter → Topic → Concept → Practice → PYQ → Performance → Analysis → Revision → Mastery'),Practice:card('Practice Center','Practice/PYQ execution foundation is present; question bank integration is not claimed complete.'),Performance:card('Performance','Scoring/state foundation is ready; complete analytics are not claimed complete.'),Assets:card('Assets & Gallery','Permission-aware asset area foundation. Full gallery processing is not claimed complete.'),Profile:`<div class="card"><b>User Control Center</b><p class="muted">Profile controls remain user-owned. Profile picture changes are blocked for 15 days after each change.</p><p>${state.profile.pictureChangedAt?`Last change: ${new Date(state.profile.pictureChangedAt).toLocaleString()}`:'No profile picture change recorded.'}</p></div>`,Settings:`<div class="grid"><div class="card"><b>Notifications</b><p>${state.settings.notifications?'Enabled':'Disabled'}</p><button class="action" id="toggleNotify">Toggle</button></div><div class="card"><b>Upgrade Guard</b><p class="muted">Read-only protection/status shell. State-changing actions require user approval.</p></div><div class="card"><b>Activity History</b><p class="muted">${state.history.length} recorded relevant events.</p></div></div>`};return map[r]||card(r,'Foundation route ready.')}
function card(t,d){return `<div class="card"><b>${t}</b><p class="muted">${d}</p></div>`}
document.addEventListener('click',e=>{if(e.target.id==='toggleNotify'){state.settings.notifications=!state.settings.notifications;log('settings','Notification preference changed by user');render()}});
document.querySelector('#sukoon').onclick=()=>alert('Sukoon.Brain shell is available. Live AI/model integration is not claimed complete in Phase 4 foundation.');
window.addEventListener('online',render);window.addEventListener('offline',render);render();
if('serviceWorker' in navigator)navigator.serviceWorker.register('6_sw.js').catch(()=>{});
