export class AcademicEngine{
 constructor(data,store){this.data=data;this.store=store;}
 getPracticeQuestions(filter,conceptId){return this.data.questions.filter(q=>q.classId===filter.classId&&(!conceptId||q.conceptId===conceptId)).map(q=>{const s=this.data.subjects.find(x=>x.id===q.subjectId);const c=this.data.concepts.find(x=>x.id===q.conceptId);return {...q,subjectName:s?.name||'',conceptTitle:c?.title||''}});}
 normalize(v){return String(v??'').trim().toLowerCase().replace(/[.,!?\s]+/g,' ');}
 checkAnswer(q,input){const a=this.normalize(input),correct=this.normalize(q.answer);let ok=a===correct;if(!ok&&q.id==='q-chem11-1')ok=a.replace(/\s/g,'')==='6.022e23'||a.includes('6.022');if(!ok&&q.id==='q-bio11-1')ok=a.includes('growth')||a.includes('वृद्धि');if(!ok&&q.id==='q-hin11-1')ok=a.includes('स्पष्ट')||a.includes('स्पष्टता');if(!ok&&q.id==='q-hin12-1')ok=a.includes('प्रमाण')||a.includes('साक्ष्य');return {correct:ok,explanation:q.explanation};}
 async recordAttempt(q,result){await this.store.addAttempt({questionId:q.id,conceptId:q.conceptId,classId:q.classId,subjectId:q.subjectId,correct:result.correct,at:new Date().toISOString()});}
 async queueRevision(conceptId){await this.store.setRevision(conceptId,{queuedAt:new Date().toISOString(),reason:'user_or_performance'});}
 async getRevisionQueue(){return this.store.getRevision();}
 async getConceptProgress(conceptId){const a=(await this.store.getAttempts()).filter(x=>x.conceptId===conceptId);const correct=a.filter(x=>x.correct).length;const accuracy=a.length?Math.round(correct/a.length*100):0;const mastery=Math.min(100,Math.round(accuracy*0.7+Math.min(a.length,5)*6));return {attempts:a.length,correct,incorrect:a.length-correct,accuracy,mastery};}
 async getOverallProgress(filter){const a=(await this.store.getAttempts()).filter(x=>x.classId===filter.classId);const correct=a.filter(x=>x.correct).length;const concepts=new Set(a.map(x=>x.conceptId));return {attempts:a.length,correct,incorrect:a.length-correct,accuracy:a.length?Math.round(correct/a.length*100):0,completedConcepts:concepts.size};}
 async getWeakConcepts(filter){const a=await this.store.getAttempts();const ids=this.data.concepts.filter(c=>c.classId===filter.classId).map(c=>c.id);return ids.map(id=>{const x=a.filter(y=>y.conceptId===id);const correct=x.filter(y=>y.correct).length;return {id,title:this.data.concepts.find(c=>c.id===id)?.title||id,accuracy:x.length?Math.round(correct/x.length*100):0,attempts:x.length};}).filter(x=>x.attempts&&x.accuracy<70).sort((a,b)=>a.accuracy-b.accuracy);}
 async getRecommendations(filter){const weak=await this.getWeakConcepts(filter);if(weak.length)return weak.map(x=>({title:`Review ${x.title}`,reason:'Low recent accuracy; revise and re-practice this concept.'}));const p=await this.getOverallProgress(filter);if(!p.attempts)return [{title:'Start with a Class 11/12 subject',reason:'No practice history yet.'}];return [{title:'Continue practice',reason:'Keep building concept consistency.'}];}
}
